kind: Namespace
apiVersion: v1
metadata:
  name: che-batleforc
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-namespace
  annotations:
    che.eclipse.org/username: Batleforc
    scheduler.alpha.kubernetes.io/node-selector: worker
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: che-batleforc-rolebinding
  namespace: che-batleforc
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
subjects:
  - kind: User
    name: Batleforc
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: eclipse-che-cheworkspaces-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: che-batleforc-rolebinding-devworkspace
  namespace: che-batleforc
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
subjects:
  - kind: User
    name: Batleforc
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: eclipse-che-cheworkspaces-devworkspace-clusterrole
  apiGroup: rbac.authorization.k8s.io