{{- if .Values.cluster.che.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: che-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/batleforc/weebo-si'
    path: 'all-in-one.argo/helm/cluster-tpl'
    helm:
      releaseName: che-cluster
      valuesObject:
        traefik:
          ips: "10.244.0.158"
        monitoring:
          {{ range $key, $value := .Values.monitoring }}
          {{ $key }}: {{ $value | toJson | indent 8 }}
          {{- end }}
        cluster:
          controlPlane:
            replicas: 1
            ram: 11Gi
          worker:
            replicas: 1
            ram: 8Gi
            autoscale: false
  destination:
    name: in-cluster
    namespace: 'che'
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
{{- end -}}
