{{- if .Values.kamalos.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kamalos
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/batleforc/weebo-si'
    path: 'all-in-one.argo/helm/kamalos'
    helm:
      releaseName: kamalos
  destination:
    name: in-cluster
    namespace: 'kamalos'
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/restrict: privileged
        pod-security.kubernetes.io/audit: privileged
    syncOptions:
    - RespectIgnoreDifferences=true
    - CreateNamespace=true
    - ServerSideApply=true
{{- end -}}