kamaji:
  version: "0.0.0+latest"
  csrSigner:
    enabled: true
    image: "ghcr.io/clastix/talos-csr-signer"
    tag: "latest"

cluster:
  name: "kamalos"
  namespace: "kamalos"
  kubeVersion: "v1.33.2"
  talosVersion: "v1.11.5"
  controlPlane:
    ip: "10.96.70.1"

workers:
  - name: "worker-1"
    ip: "10.96.70.2"
    img: "https://factory.talos.dev/image/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b/v1.11.5/openstack-amd64.qcow2"
    cpu:
      cores: 2
      threads: 1
    ram: "10Gi"
    storage: "20Gi"
