kamaji:
  version: "0.0.0+latest"
  csrSigner:
    enabled: true
    image: "ghcr.io/clastix/talos-csr-signer"
    tag: "latest"

cluster:
  name: "kamalos"
  namespace: "kamalos"
  kubeVersion: "v1.33.2"
  talosVersion: "v1.11.5"
  controlPlane:
    ip: "10.96.70.1"
  network:
    podSubnets: 10.245.0.0/16
    serviceSubnets: 10.128.0.0/12
  vpn:
    enabled: true
    managementUrl: "https://netbird.4.weebo.fr:443"
    adminUrl: "https://netbird.4.weebo.fr:443"

workers:
  - name: "worker-1"
    ip: "10.244.0.43"
    source: "registry"
    img: "docker://harbor.4.weebo.fr/talos/vpn-metal/qcow:v1.11.5"
    cpu:
      cores: 2
      threads: 1
    ram: "10Gi"
    storage: "20Gi"
  - name: "worker-2"
    ip: "10.244.0.188"
    source: "registry"
    img: "docker://harbor.4.weebo.fr/talos/vpn-metal/qcow:v1.11.5"
    cpu:
      cores: 2
      threads: 1
    ram: "8Gi"
    storage: "20Gi"
