kamaji:
  version: "0.0.0+latest"
  csr_signer:
    enabled: true
    image: "ghcr.io/clastix/talos-csr-signer"
    tag: "latest"

cluster:
  name: "kamalos"
  namespace: "kamalos"
  kubeVersion: "v1.33.2"
  talosVersion: "v1.11.5"
  controlPlane:
    ip: "10.96.70.1"

workers:
  - ip: ""
